//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.name {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.name.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking: .
        /// </summary>
        internal static string common_checking {
            get {
                return ResourceManager.GetString("common_checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Back.
        /// </summary>
        internal static string common_CodeBack {
            get {
                return ResourceManager.GetString("common_CodeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last 50 cabinet history records.
        /// </summary>
        internal static string common_history50cabinet {
            get {
                return ResourceManager.GetString("common_history50cabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judge.
        /// </summary>
        internal static string common_judge {
            get {
                return ResourceManager.GetString("common_judge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        internal static string common_language {
            get {
                return ResourceManager.GetString("common_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Output Over Time.
        /// </summary>
        internal static string common_multichart {
            get {
                return ResourceManager.GetString("common_multichart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG cabinet count chart.
        /// </summary>
        internal static string common_ngchart {
            get {
                return ResourceManager.GetString("common_ngchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending cabinet count chart.
        /// </summary>
        internal static string common_pendingchart {
            get {
                return ResourceManager.GetString("common_pendingchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK/NG/PENDING Cabinet Count Chart.
        /// </summary>
        internal static string common_stackchart {
            get {
                return ResourceManager.GetString("common_stackchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Update.
        /// </summary>
        internal static string common_TimeUpdate {
            get {
                return ResourceManager.GetString("common_TimeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK/NG ratio chart.
        /// </summary>
        internal static string common_titlepiechart {
            get {
                return ResourceManager.GetString("common_titlepiechart", resourceCulture);
            }
        }
    }
}
